"""Reporters turn a scan result into output formats.

Two are provided: structured JSON (machine-readable, for pipelines) and
Markdown (human-readable findings report). Both consume the same list of
Findings, so adding a format never touches the analysers.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..findings import Finding, Severity


def _sorted_findings(findings: list[Finding]) -> list[Finding]:
    # Highest severity first, then by analyser and id for stability.
    return sorted(
        findings,
        key=lambda f: (-f.severity.rank, f.analyser, f.id),
    )


def _severity_counts(findings: list[Finding]) -> dict[str, int]:
    counts = {s.value: 0 for s in Severity}
    for f in findings:
        counts[f.severity.value] += 1
    return counts


def build_summary(image: str, image_sha256: str, findings: list[Finding],
                  meta: dict[str, Any]) -> dict[str, Any]:
    return {
        "tool": "fw-scout",
        "generated": datetime.now(timezone.utc).isoformat(),
        "image": image,
        "image_sha256": image_sha256,
        "meta": meta,
        "severity_counts": _severity_counts(findings),
        "finding_count": len(findings),
    }


def write_json(path: Path, summary: dict[str, Any],
               findings: list[Finding]) -> None:
    payload = {
        "summary": summary,
        "findings": [f.to_dict() for f in _sorted_findings(findings)],
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


_SEV_BADGE = {
    Severity.CRITICAL: "CRITICAL",
    Severity.HIGH: "HIGH",
    Severity.MEDIUM: "MEDIUM",
    Severity.LOW: "LOW",
    Severity.INFO: "INFO",
}


def write_markdown(path: Path, summary: dict[str, Any],
                   findings: list[Finding]) -> None:
    lines: list[str] = []
    lines.append(f"# fw-scout findings report")
    lines.append("")
    lines.append(f"- **Image:** `{summary['image']}`")
    lines.append(f"- **SHA-256:** `{summary['image_sha256']}`")
    lines.append(f"- **Generated:** {summary['generated']}")
    lines.append(f"- **Extraction tool:** {summary['meta'].get('extraction_tool', 'n/a')}")
    lines.append(f"- **Rootfs roots analysed:** {summary['meta'].get('rootfs_count', 0)}")
    lines.append("")

    counts = summary["severity_counts"]
    lines.append("## Severity summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM,
                Severity.LOW, Severity.INFO]:
        lines.append(f"| {_SEV_BADGE[sev]} | {counts.get(sev.value, 0)} |")
    lines.append(f"| **Total** | **{summary['finding_count']}** |")
    lines.append("")

    lines.append("## Findings")
    lines.append("")
    if not findings:
        lines.append("_No findings._")
    for f in _sorted_findings(findings):
        lines.append(f"### [{_SEV_BADGE[f.severity]}] {f.title}")
        lines.append("")
        lines.append(f"- **id:** `{f.id}`  ·  **analyser:** {f.analyser}"
                     f"  ·  **confidence:** {f.confidence}")
        if f.weakness:
            lines.append(f"- **weakness:** {f.weakness}")
        if f.path:
            lines.append(f"- **location:** `{f.path}`")
        if f.evidence:
            lines.append(f"- **evidence:** `{f.evidence}`")
        if f.detail:
            lines.append("")
            lines.append(f.detail)
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by fw-scout. Findings are static-analysis "
                 "observations; confirm against a live device before "
                 "asserting exploitability._")
    path.write_text("\n".join(lines), encoding="utf-8")
